### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by gngeorgiev** [go-neutrino/neutrino-javascript-sdk#1]
- [X] - Realtime filtering support
- [ ] - Write unit/integration tests
- [ ] - Write a proper readme
- [ ] - Update readme
- [ ] - Docs
- [ ] - REST filtering
- [ ] - Filtering ReQL expressions
- [ ] - Realtime sorting
- [ ] - REST sorting
